version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: golang_brand
  app:
    restart: always
    ports:
    - "5500:5500"
    build: .
    environment:
      DB_TYPE: postgres
      URL: "http://localhost"
      PORT: 5500
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: golang_brand
      DB_TEST_DATABASE: golang_test_brand
      JWT_SECRET: secret
    depends_on:
      - postgres
